services:
  # База данных
  mongodb:
    image: mongo:6
    container_name: task-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - task-network

  # Бэкенд
  backend:
    build: ./backend
    container_name: task-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?authSource=admin
      - CLIENT_URL=http://localhost:${FRONTEND_PORT}
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - mongodb
    networks:
      - task-network

  # Фронтенд
  frontend:
    build: ./frontend
    container_name: task-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - task-network

volumes:
  mongo_data:

networks:
  task-network:
    driver: bridge
